# Generated by Django 6.1.1 on 2026-09-30 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoBomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ON', 'Encendida'), ('OFF', 'Apagada')], max_length=3)),
                ('origen', models.CharField(default='mqtt', max_length=16)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('troncal', 'Troncal'), ('rama_a', 'Rama A'), ('rama_b', 'Rama B')], max_length=16, unique=True)),
                ('nombre', models.CharField(max_length=64)),
                ('k_factor', models.FloatField(default=7.5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ResumenMinuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(db_index=True)),
                ('n', models.IntegerField()),
                ('suma', models.FloatField()),
                ('promedio', models.FloatField()),
                ('minimo', models.FloatField()),
                ('maximo', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_minuto', to='sensores.sensor')),
            ],
            options={
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['sensor', '-inicio'], name='sensores_re_sensor__45bb61_idx')],
                'unique_together': {('sensor', 'inicio')},
            },
        ),
        migrations.CreateModel(
            name='ResumenHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(db_index=True)),
                ('n', models.IntegerField()),
                ('suma', models.FloatField()),
                ('promedio', models.FloatField()),
                ('minimo', models.FloatField()),
                ('maximo', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_hora', to='sensores.sensor')),
            ],
            options={
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['sensor', '-inicio'], name='sensores_re_sensor__e503b2_idx')],
                'unique_together': {('sensor', 'inicio')},
            },
        ),
        migrations.CreateModel(
            name='ResumenDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(db_index=True)),
                ('n', models.IntegerField()),
                ('suma', models.FloatField()),
                ('promedio', models.FloatField()),
                ('minimo', models.FloatField()),
                ('maximo', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_dia', to='sensores.sensor')),
            ],
            options={
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['sensor', '-inicio'], name='sensores_re_sensor__ee5cd0_idx')],
                'unique_together': {('sensor', 'inicio')},
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.FloatField(help_text='Caudal L/min')),
                ('ts_nodo', models.FloatField(blank=True, help_text='Epoch del ESP32', null=True)),
                ('ts_ingesta', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='sensores.sensor')),
            ],
            options={
                'ordering': ['-ts_ingesta'],
                'indexes': [models.Index(fields=['sensor', '-ts_ingesta'], name='sensores_le_sensor__f48723_idx')],
            },
        ),
    ]
